name: Market Data ETL

on:
  schedule:
    # Run every 5 minutes during market hours (9:30 AM - 4:00 PM ET, Mon-Fri)
    # Cron runs in UTC, so ET hours are UTC-5 (or UTC-4 during DST)
    # 9:30 AM ET = 2:30 PM UTC (DST) or 1:30 PM UTC (standard)
    # 4:00 PM ET = 9:00 PM UTC (DST) or 8:00 PM UTC (standard)
    - cron: '*/5 13-20 * * 1-5'  # Every 5 min, 1:00 PM - 8:00 PM UTC, Mon-Fri (covers both DST and standard time)

  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL script
        env:
          APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python ops/scripts/market_data_etl.py --force

      - name: Check ETL status
        if: failure()
        run: echo "ETL failed - check logs above"
