name: RL Trading Agent

on:
  schedule:
    # Run every 5 minutes during market hours (synchronized with ETL)
    # Runs 2 minutes after ETL to ensure fresh data is available
    - cron: '2-57/5 13-20 * * 1-5'  # Every 5 min at :02, :07, :12, etc., Mon-Fri

  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trading agent
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python ops/scripts/rl_trading_agent.py

      - name: Check trading status
        if: failure()
        run: echo "Trading agent failed - check logs above"
